version: '3'

vars:
  NORMAL: foot git sway tmux vim
  NO_FOPLD: code ssh zsh

tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list-all
    silent: true

  stow:
    desc: Link dotfiles
    dir: apps
    cmds:
      - stow --adopt -v -t ~ {{ .NORMAL }}
      - stow --adopt -v -t ~ --no-folding {{ .NO_FOPLD }}
      - git restore .
      - stow -v -t ~ {{ .NORMAL }}
      - stow -v -t ~ --no-folding {{ .NO_FOPLD }}

  unstow:
    desc: Unlink dotfiles
    dir: apps
    cmds:
      - stow -v -t ~ -D {{ .NORMAL }} {{ .NO_FOPLD }}

